#!/bin/bash
#PBS -l nodes=1:ppn=1,walltime=1:00:00
#PBS -N app-reslice-roi-dwi
#PBS -l vmem=16gb
#PBS -V

set -e

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

echo "reslicing rois"
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:6.0.0 ./reslice.sh
